// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJfts0ptaN4Bi4TdVboqXSfjF7YtgE-W0',
    appId: '1:185047983787:web:77fc0199e27bbdd53cf9ee',
    messagingSenderId: '185047983787',
    projectId: 'es-pi3-2026-t3-g22',
    authDomain: 'es-pi3-2026-t3-g22.firebaseapp.com',
    storageBucket: 'es-pi3-2026-t3-g22.firebasestorage.app',
    measurementId: 'G-501YEQ9GKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7QgHGkrk-2uDOLERsQ1AN9_Pbmchz1SI',
    appId: '1:185047983787:android:f429b85153849f5f3cf9ee',
    messagingSenderId: '185047983787',
    projectId: 'es-pi3-2026-t3-g22',
    storageBucket: 'es-pi3-2026-t3-g22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5YehUu_7IgDvJi9f0MY1QmwN_MkzZdig',
    appId: '1:185047983787:ios:84e2fefaf2b51f743cf9ee',
    messagingSenderId: '185047983787',
    projectId: 'es-pi3-2026-t3-g22',
    storageBucket: 'es-pi3-2026-t3-g22.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5YehUu_7IgDvJi9f0MY1QmwN_MkzZdig',
    appId: '1:185047983787:ios:84e2fefaf2b51f743cf9ee',
    messagingSenderId: '185047983787',
    projectId: 'es-pi3-2026-t3-g22',
    storageBucket: 'es-pi3-2026-t3-g22.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJfts0ptaN4Bi4TdVboqXSfjF7YtgE-W0',
    appId: '1:185047983787:web:ff06372001e0c3603cf9ee',
    messagingSenderId: '185047983787',
    projectId: 'es-pi3-2026-t3-g22',
    authDomain: 'es-pi3-2026-t3-g22.firebaseapp.com',
    storageBucket: 'es-pi3-2026-t3-g22.firebasestorage.app',
    measurementId: 'G-T2S4G7S48N',
  );

}